name: Ruby CI

on:
  push:

permissions:
  contents: read

jobs:
  test:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - 3.1.0
          - 3.0.0
          - 2.7.6
        experimental: [false]
        include:
          - ruby-version: head
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v3

     - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake
